using System;
using System.Collections.Generic;
using System.Text;

namespace ProjectEuler.Problems
{
    /// <summary>
    /// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
    /// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
    /// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
    /// </summary>
    public class Problem2_EvenFibonacciNumbers
    {
        const int input = 4000000;
        public void Solve()
        {
            int total = 0;
            int count = 1;
            int previousNumber = 1;
            

            while(count < input) 
            {
                int temp = count;
                count += previousNumber;
                previousNumber = temp;

                if(count %2 == 0) 
                    total += count; 
            }
           
          
            Console.WriteLine($"Sum of all Even Fibonacci numbers below {input} = {total}");

        }
    }
}
